name: Build and push a container image
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: sudo apt -yqq --no-install-recommends install zsh
        env:
          DEBIAN_FRONTEND: noninteractive

      - run: pip3 install -r dev-requirements.txt

      - name: login to container registry
        run: podman login -u "$QUAY_USER" -p "$QUAY_TOKEN" quay.io
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

      - name: configure sops secrets
        run: >-
          mkdir -p "$HOME/.config/sops/age" &&
          echo "$SOPS_SECRET" >"$HOME/.config/sops/age/keys.txt"
        env:
          SOPS_SECRET: ${{ secrets.SOPS_SECRET }}

      - name: do the thing
        run: ./mk/ctnr.sh -d prod --push
