name: Build and upload Arch Linux package for Silicon with Solidity (and ligature) support
on:
  schedule:
    - cron: '38 4 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: do the thing
        run: |
          cd mk/silicon
          ./archpkg.sh

          pkg="$(basename "$(find . -name *.pkg.*)")"
          mkdir -p "${RUNNER_TEMP}/dist"
          mv "$pkg" "${RUNNER_TEMP}/dist/${pkg}"

          printf '%s\n' "${RUNNER_TEMP}/dist/"
          ls -lh "${RUNNER_TEMP}/dist/"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ runner.temp }}/dist/*
          fail_on_unmatched_files: true
